[project]
name = "searchindex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autocorrect>=2.6.1",
    "faiss-cpu>=1.15.0",
    "polars>=1.43.2",
    "sentence-transformers>=5.7.0",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
    "typer>=0.27.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "ty>=0.0.71",
]

